### ISSUE TITLE
Setup monorepo

### ISSUE THREAD

**Issue by adamjamesturner93** [Imperial-College-AND-Digital/amputee-rehab-app-monorepo#1]
- [x] Setup Next JS web app
- [x] Setup initial express API

**Comment by adamjamesturner93** [comment]
@all-contributors please add @adamjamesturner93 for infrastructure and code

**Comment by adamjamesturner93** [comment]
React Native app not created

**Comment by anitaschan** [comment]
Moving creation of React Native App to ticket #33
